export const COUNTRY_CODES = [
  { name: 'Côte d’Ivoire', code: '+225' }, { name: 'Togo', code: '+228' }, { name: 'Bénin', code: '+229' }, { name: 'Ghana', code: '+233' },
  { name: 'Nigeria', code: '+234' }, { name: 'Sénégal', code: '+221' }, { name: 'Mali', code: '+223' }, { name: 'Burkina Faso', code: '+226' },
  { name: 'Guinée', code: '+224' }, { name: 'Cameroun', code: '+237' }, { name: 'Gabon', code: '+241' }, { name: 'Congo', code: '+242' },
  { name: 'République démocratique du Congo', code: '+243' }, { name: 'Afrique du Sud', code: '+27' }, { name: 'Algérie', code: '+213' }, { name: 'Maroc', code: '+212' },
  { name: 'Tunisie', code: '+216' }, { name: 'Égypte', code: '+20' }, { name: 'Éthiopie', code: '+251' }, { name: 'Kenya', code: '+254' },
  { name: 'Tanzanie', code: '+255' }, { name: 'Ouganda', code: '+256' }, { name: 'Rwanda', code: '+250' }, { name: 'Madagascar', code: '+261' },
  { name: 'Allemagne', code: '+49' }, { name: 'Autriche', code: '+43' }, { name: 'Belgique', code: '+32' }, { name: 'Espagne', code: '+34' },
  { name: 'France', code: '+33' }, { name: 'Italie', code: '+39' }, { name: 'Luxembourg', code: '+352' }, { name: 'Pays-Bas', code: '+31' },
  { name: 'Portugal', code: '+351' }, { name: 'Royaume-Uni', code: '+44' }, { name: 'Suisse', code: '+41' }, { name: 'Irlande', code: '+353' },
  { name: 'Danemark', code: '+45' }, { name: 'Finlande', code: '+358' }, { name: 'Norvège', code: '+47' }, { name: 'Suède', code: '+46' },
  { name: 'Grèce', code: '+30' }, { name: 'Pologne', code: '+48' }, { name: 'Roumanie', code: '+40' }, { name: 'Ukraine', code: '+380' },
  { name: 'Russie', code: '+7' }, { name: 'Turquie', code: '+90' }, { name: 'Canada', code: '+1' }, { name: 'États-Unis', code: '+1' },
  { name: 'Mexique', code: '+52' }, { name: 'Brésil', code: '+55' }, { name: 'Argentine', code: '+54' }, { name: 'Chili', code: '+56' },
  { name: 'Colombie', code: '+57' }, { name: 'Pérou', code: '+51' }, { name: 'Australie', code: '+61' }, { name: 'Nouvelle-Zélande', code: '+64' },
  { name: 'Chine', code: '+86' }, { name: 'Corée du Sud', code: '+82' }, { name: 'Inde', code: '+91' }, { name: 'Indonésie', code: '+62' },
  { name: 'Israël', code: '+972' }, { name: 'Japon', code: '+81' }, { name: 'Malaisie', code: '+60' }, { name: 'Philippines', code: '+63' },
  { name: 'Singapour', code: '+65' }, { name: 'Thaïlande', code: '+66' }, { name: 'Vietnam', code: '+84' }, { name: 'Arabie saoudite', code: '+966' },
  { name: 'Émirats arabes unis', code: '+971' }, { name: 'Qatar', code: '+974' }, { name: 'Jordanie', code: '+962' }, { name: 'Liban', code: '+961' },
  { name: 'Islande', code: '+354' }, { name: 'Malte', code: '+356' }, { name: 'Chypre', code: '+357' }, { name: 'Estonie', code: '+372' },
  { name: 'Lettonie', code: '+371' }, { name: 'Lituanie', code: '+370' }, { name: 'Slovaquie', code: '+421' }, { name: 'Slovénie', code: '+386' },
  { name: 'Croatie', code: '+385' }, { name: 'Serbie', code: '+381' }, { name: 'Bulgarie', code: '+359' }, { name: 'Hongrie', code: '+36' },
  { name: 'Haïti', code: '+509' }, { name: 'Cuba', code: '+53' }, { name: 'Jamaïque', code: '+1876' }, { name: 'Panama', code: '+507' },
  { name: 'Costa Rica', code: '+506' }, { name: 'Guatemala', code: '+502' }, { name: 'Bolivie', code: '+591' }, { name: 'Équateur', code: '+593' }
].sort((firstCountry, secondCountry) => firstCountry.name.localeCompare(secondCountry.name, 'fr'));
